# Generated by Django 5.2.4 on 2025-09-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_propertycategory_propertytype_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytype',
            old_name='category',
            new_name='property_category',
        ),
    ]
