# Generated by Django 5.2.4 on 2025-09-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_propertyunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunit',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
