# Generated by Django 5.2.4 on 2025-09-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_propertyunit_rent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunit',
            name='vacant_status',
            field=models.BooleanField(default=True),
        ),
    ]
