# Generated by Django 5.2.4 on 2025-09-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_tenant_propertylease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='Occupation',
            new_name='occupation',
        ),
    ]
